Repository Jandy-SeoulTech/Jandy_Web_Front, pull requests merged in 2021-09, with the labels that each got.

#26 채널 프로필 멤버 모달 구현
  src/components/channel/ChannelProfile.jsx
  src/components/channel/CreateChannel.jsx
  src/components/common/ModalUserCard.jsx
  src/components/common/ProfileModal.jsx
  src/components/profile/Profile.jsx
  src/containers/channel/ChannelProfileContainer.jsx
  src/containers/channel/CreateChannelContainer.jsx
  src/containers/profile/ProfileContainer.jsx
  src/modules/channel.js
  src/pages/channel/CreateChannelPage.jsx
Labels: Develop

#46 Refactor: auth모듈 redux-pender 적용, signin 로직 수정
  .prettierrc
  package.json
  src/components/auth/OAuth.jsx
  src/components/channel/MyChannel.jsx
  src/components/chat/ChattingRoom.jsx
  src/components/profile/Profile.jsx
  src/containers/auth/OAuthContainer.jsx
  src/containers/auth/SigninContainer.jsx
  src/containers/auth/SignupContainer.jsx
  src/containers/channel/ChannelProfileContainer.jsx
  src/containers/channel/EditChannelContainer.jsx
  src/containers/channel/MyChannelContainer.jsx
  src/containers/chat/ChannelTalkContainer.jsx
  src/containers/chat/ChattingRoomContainer.jsx
  src/containers/profile/ProfileContainer.jsx
  src/index.js
  src/lib/api/auth.js
  src/lib/api/channel.js
  src/lib/api/chat.js
  src/lib/api/profile.js
  src/lib/api/room.js
  src/lib/util/createRequestSaga.js
  src/modules/auth.js
  src/modules/channel.js
  src/modules/chat.js
  src/modules/image.js
  src/modules/index.js
  src/modules/loading.js
  src/modules/profile.js
  src/modules/room.js
  src/modules/user.js
  src/modules/write.js
  src/routers/ChannelRouter.jsx
  src/store.js
  yarn.lock
Labels: Refactoring 🚜

#48 유저 프로필 관련 네이밍 변경
  src/components/profile/Profile.jsx
  src/containers/profile/ProfileContainer.jsx
  src/lib/api/channel.js
  src/modules/channel.js
Labels: Refactoring 🚜

#50 채널 재능 공유 요청 페이지 데이터 연동
  src/components/channel/ChannelPostList.jsx
  src/containers/channel/ChannelPostListContainer.jsx
  src/lib/api/channel.js
  src/modules/channel.js
Labels: Feature ✨

#51 채널 홈 페이지 데이터 연동
  src/components/channel/ChannelHome.jsx
  src/components/channel/PostCard.jsx
  src/containers/channel/ChannelHomeContainer.jsx
  src/lib/assets/postIcon.svg
  src/modules/channel.js
Labels: Feature ✨

#52 채널 재능요청 포스트 데이터 연동, 채팅방 생성
  src/components/channel/ChannelPost.jsx
  src/containers/channel/ChannelPostContainer.jsx
  src/containers/channel/ChannelPostListContainer.jsx
  src/lib/api/channel.js
  src/modules/channel.js
Labels: Feature ✨

#54 채널 홈 페이지 콘텐츠 없는 경우 메시지 표시
  src/components/channel/ChannelHome.jsx
Labels: Feature ✨

#57 채널 재능 공유 요청 페이지 게시물 없는 경우 경계선 제거
  .prettierrc
  package.json
  src/components/auth/OAuth.jsx
  src/components/channel/ChannelPostList.jsx
  src/components/channel/MyChannel.jsx
  src/components/chat/ChattingRoom.jsx
  src/components/profile/Profile.jsx
  src/containers/auth/OAuthContainer.jsx
  src/containers/auth/SigninContainer.jsx
  src/containers/auth/SignupContainer.jsx
  src/containers/channel/ChannelPostListContainer.jsx
  src/containers/channel/ChannelProfileContainer.jsx
  src/containers/channel/EditChannelContainer.jsx
  src/containers/channel/MyChannelContainer.jsx
  src/containers/chat/ChannelTalkContainer.jsx
  src/containers/chat/ChattingRoomContainer.jsx
  src/containers/profile/ProfileContainer.jsx
  src/index.js
  src/lib/api/auth.js
  src/lib/api/channel.js
  src/lib/api/chat.js
  src/lib/api/profile.js
  src/lib/api/room.js
  src/lib/util/createRequestSaga.js
  src/modules/auth.js
  src/modules/channel.js
  src/modules/chat.js
  src/modules/image.js
  src/modules/index.js
  src/modules/loading.js
  src/modules/profile.js
  src/modules/room.js
  src/modules/user.js
  src/modules/write.js
  src/routers/ChannelRouter.jsx
  src/store.js
  yarn.lock
Labels: Refactoring 🚜

#59 채널 재능 공유 요청 페이지 게시물 없는 경우 경계선 제거
  src/components/channel/ChannelPostList.jsx
Labels: Refactoring 🚜
