Repository Jandy-SeoulTech/Jandy_Web_Front, pull requests merged in 2021-11, with the labels that each got.

#221 Refactor: 전체 리뷰 모달에서 채널 버튼 누르면 채널 홈 이동
  src/components/common/ModalReviewCard.jsx
Labels: Refactoring 🚜

#212 fix: 잡담방 두번 렌더링 해결 (#208)
  src/containers/channel/ChannelProfileContainer.jsx
Labels: Bug 🐛

#206 fix: 모아보기 패이지네이션 오류 해결 (#203)
  src/containers/channel/ChannelArchiveListContainer.jsx
Labels: Bug 🐛

#216 Refactor: 프로필 등록 페이지 내 프로필 사진 등록해도 건너뛰기 표시
  src/components/profile/NextButton.jsx
  src/containers/profile/UploadProfileContainer.jsx
Labels: Refactoring 🚜

#222 fix: 채널프로필 수정 시 카테고리 설정 픽스 (#211)
  .netlify/state.json
  netlify.toml
  src/modules/write.js
Labels: Bug 🐛

#224 feat: 네이버 OAuth 콜백주소 변경 (#223)
  src/containers/auth/OAuthContainer.jsx
Labels: Bug 🐛

#219 Fix: 닉네임 중복 확인
  package.json
  src/lib/api/auth.js
  src/lib/util/createRequestSaga.js
  src/modules/auth.js
  src/modules/index.js
  src/modules/loading.js
  src/store.js
  yarn.lock
Labels: Bug 🐛, Refactoring 🚜
