Repository Jandy-SeoulTech/Jandy_Web_Front, pull requests merged in 2021-10, with the labels that each got.

#66 Fix: 회원가입 오류 해결
  src/components/auth/Signup.jsx
  src/containers/auth/SignupContainer.jsx
  src/lib/api/image.js
  src/modules/auth.js
Labels: Bug 🐛

#70 Fix: 닉네임 등록 에러 해결
  src/containers/profile/SetNicknameContainer.jsx
  src/modules/auth.js
  src/modules/user.js
Labels: Bug 🐛

#67 재능 공유 요청 게시물 작성
  package.json
  src/components/channel/ChannelPostList.jsx
  src/components/channel/ChannelPostWriting.jsx
  src/containers/channel/ChannelPostWritingContainer.jsx
  src/lib/api/channel.js
  src/modules/channel.js
  src/pages/channel/ChannelPostWritingPage.jsx
  src/routers/ChannelRouter.jsx
  yarn.lock
Labels: Feature ✨

#72 브라우저리스트 업데이트
  package.json
  yarn.lock
Labels: Bug 🐛

#80 재능공유요청/아카이브 MD 에디터 구현
  src/components/channel/ChannelPost.jsx
  src/components/channel/ChannelPostEdit.jsx
  src/components/channel/ChannelPostWriting.jsx
  src/components/channel/CreateChannel.jsx
  src/containers/channel/ChannelPostContainer.jsx
  src/containers/channel/ChannelPostEditContainer.jsx
  src/containers/channel/ChannelPostWritingContainer.jsx
  src/containers/channel/CreateChannelContainer.jsx
  src/lib/util/editorConfig.js
  src/modules/channel.js
  src/pages/channel/ChannelPostEditPage.jsx
  src/pages/channel/ChannelPostWritingPage.jsx
  src/pages/channel/CreateChannelPage.jsx
  src/routers/ChannelRouter.jsx
  src/setupProxy.js
Labels: Bug 🐛, Feature ✨

#81 Post 관련 로직 분리, 경로 변경
  src/components/UploadProfileForms/InterestTalent.jsx
  src/components/UploadProfileForms/WellTalent.jsx
  src/components/channel/ChannelNav.jsx
  src/components/channel/ChannelPost.jsx
  src/components/channel/ChannelPostList.jsx
  src/components/channel/EditChannel.jsx
  src/components/channel/PostCard.jsx
  src/components/common/Button.jsx
  src/components/common/Comment.jsx
  src/components/common/Loading.jsx
  src/components/common/TagBox.jsx
  src/components/post/CreateRoomModal.jsx
  src/components/post/EditPost.jsx
  src/components/post/Post.jsx
  src/components/post/PostButtonList.jsx
  src/components/post/PostEditor.jsx
  src/components/post/PostStatusIcon.jsx
  src/containers/channel/ChannelHomeContainer.jsx
  src/containers/channel/ChannelPostContainer.jsx
  src/containers/channel/ChannelPostListContainer.jsx
  src/containers/channel/ChannelProfileContainer.jsx
  src/containers/common/CommentContainer.jsx
  src/containers/post/EditPostContainer.jsx
  src/containers/post/PostButtonListContainer.jsx
  src/containers/post/PostContainer.jsx
  src/lib/api/channel.js
  src/lib/api/comment.js
  src/lib/api/post.js
  src/lib/api/posts.js
  src/lib/util/postStatus.js
  src/lib/util/postType.js
  src/modules/channel.js
  src/modules/comment.js
  src/modules/index.js
  src/modules/post.js
  src/modules/room.js
  src/modules/write.js
  src/pages/channel/ChannelPostPage.jsx
  src/pages/channel/ChannelPostWritingPage.jsx
  src/pages/channel/EditPostPage.jsx
  src/routers/ChannelRouter.jsx
Labels: Refactoring 🚜, Feature ✨

#82 포스트 리스트 반응형 수정
  src/components/channel/ChannelPostList.jsx
  src/components/post/Post.jsx
  src/components/post/PostButtonList.jsx
  src/components/post/PostEditor.jsx
  src/components/post/PostStatusIcon.jsx
  src/containers/channel/ChannelPostListContainer.jsx
Labels: Feature ✨

#84 검색 페이지, 라우터 생성
  src/components/common/Header.jsx
  src/components/search/Search.jsx
  src/containers/common/HeaderContainer.jsx
  src/containers/search/SearchContainer.jsx
  src/pages/search/SearchPage.jsx
  src/routers/index.js
Labels: Feature ✨

#214 Refactor: 아카이브 카드 랜덤 배경색 수정
  src/lib/util/random.js
Labels: Refactoring 🚜

#215 Refactor: 프로필 페이지 내 긍정 리뷰 한 줄에 하나씩 보여주기
  src/components/profile/Profile.jsx
Labels: Refactoring 🚜

#217 Refactor: 회원가입 비밀번호 입력 placeholder
  src/components/auth/Signup.jsx
  src/lib/util/validate.js
Labels: Refactoring 🚜

#218 Fix: 재능 태그 빈칸 입력 수정
  src/components/TextField/TagInput.jsx
  src/components/profile/setting/ProfileSetting.jsx
Labels: Bug 🐛
